from enum import Enum


class MessageLog:
    TR_DTM = 'TR_DTM'
    NAAC_DSC = 'NAAC_DSC'
    EBNK_MED_DSC = 'EBNK_MED_DSC'
    E_FNC_CUSNO = 'E_FNC_CUSNO'
    E_FNC_USRID = 'E_FNC_USRID'
    E_FNC_COPR_ID = 'E_FNC_COPR_ID'
    COPR_DS = 'COPR_DS'
    LANG_DS = 'LANG_DS'
    E_FNC_USR_OS_DSC = 'E_FNC_USR_OS_DSC'
    E_FNC_USR_TELNO = 'E_FNC_USR_TELNO'
    E_FNC_USR_IPADR = 'E_FNC_USR_IPADR'
    E_FNC_LGIN_DSC = 'E_FNC_LGIN_DSC'
    E_FNC_TR_ACNO = 'E_FNC_TR_ACNO'
    RMS_SVC_C = 'RMS_SVC_C'
    INQ_CND_CLF_ID = 'INQ_CND_CLF_ID'
    INQ_CND_VAL = 'INQ_CND_VAL'
    E_FNC_USR_DVIC_INF_CNTN = 'E_FNC_USR_DVIC_INF_CNTN'
    E_FNC_USR_ACS_DSC = 'E_FNC_USR_ACS_DSC'
    E_FNC_MED_SVCID = 'E_FNC_MED_SVCID'
    E_FNC_MED_SVRNM = 'E_FNC_MED_SVRNM'
    E_FNC_RSP_C = 'E_FNC_RSP_C'
    EXE_YN = 'EXE_YN'
    STD_GBL_ID = 'STD_GBL_ID'
    TRANSFER_ACNO = 'TRANSFER_ACNO'
    CST_NAM = 'CST_NAM'
    COMMON_PUBLIC_IP = 'COMMON_PUBLIC_IP'
    Amount = 'Amount'
    E_FNC_TR_ACNO_C = 'E_FNC_TR_ACNO_C'
    IO_EA_PW_CD_DS1 = 'IO_EA_PW_CD_DS1'
    IO_EA_PW_CD_DS2 = 'IO_EA_PW_CD_DS2'
    IO_EA_PW_CD_DS3 = 'IO_EA_PW_CD_DS3'
    PRE_ASSIGN_YN = 'PRE_ASSIGN_YN'
    SMS_AUTHEN_YN = 'SMS_AUTHEN_YN'
    EXCEPT_REGIST = 'EXCEPT_REGIST'
    EXCEPTION_ADD_AUTHEN_YN = 'EXCEPTION_ADD_AUTHEN_YN'
    SMART_AUTHEN_YN = 'SMART_AUTHEN_YN'
    ATTC_DS = 'ATTC_DS'
    CHRR_TELNO = 'CHRR_TELNO'
    CHRR_TELNO1 = 'CHRR_TELNO1'
    RG_TELNO = 'RG_TELNO'
    FTR_DS2 = 'FTR_DS2'
    LS_FTR_TRDT = 'LS_FTR_TRDT'
    LS_TRDT = 'LS_TRDT'
    RV_AC_DGN_YN2 = 'RV_AC_DGN_YN2'
    IO_EA_DRW_AC_NAME1 = 'IO_EA_DRW_AC_NAME1'
    IO_EA_RV_ACTNM1 = 'IO_EA_RV_ACTNM1'
    IO_EA_RMT_FEE1 = 'IO_EA_RMT_FEE1'
    IO_EA_DD1_FTR_LMT3 = 'IO_EA_DD1_FTR_LMT3'
    IO_EA_TM1_FTR_LMT3 = 'IO_EA_TM1_FTR_LMT3'
    IO_EA_DPZ_PL_IMP_BAC = 'IO_EA_DPZ_PL_IMP_BAC'
    IO_EA_TOT_BAC6 = 'IO_EA_TOT_BAC6'
    pc_publicIP1 = 'pc_publicIP1'
    pc_publicIP2 = 'pc_publicIP2'
    pc_publicIP3 = 'pc_publicIP3'
    pc_privateIP1 = 'pc_privateIP1'
    pc_privateIP2 = 'pc_privateIP2'
    pc_privateIP3 = 'pc_privateIP3'
    pc_isProxy = 'pc_isProxy'
    pc_proxyIP1 = 'pc_proxyIP1'
    pc_proxyIP2 = 'pc_proxyIP2'
    pc_isVpn = 'pc_isVpn'
    pc_vpnIP1 = 'pc_vpnIP1'
    pc_vpnIP2 = 'pc_vpnIP2'
    pc_macAddr1 = 'pc_macAddr1'
    pc_macAddr2 = 'pc_macAddr2'
    pc_macAddr3 = 'pc_macAddr3'
    pc_macAddr4 = 'pc_macAddr4'
    pc_macAddr5 = 'pc_macAddr5'
    pc_macAddr6 = 'pc_macAddr6'
    pc_logicalMac1 = 'pc_logicalMac1'
    pc_logicalMac2 = 'pc_logicalMac2'
    pc_logicalMac3 = 'pc_logicalMac3'
    pc_logicalMac4 = 'pc_logicalMac4'
    pc_logicalMac5 = 'pc_logicalMac5'
    pc_logicalMac6 = 'pc_logicalMac6'
    pc_hddSerial1 = 'pc_hddSerial1'
    pc_hddSerial2 = 'pc_hddSerial2'
    pc_hddSerial3 = 'pc_hddSerial3'
    pc_cpuID = 'pc_cpuID'
    pc_mbSn = 'pc_mbSn'
    pc_winVer = 'pc_winVer'
    pc_isVm = 'pc_isVm'
    pc_vmName = 'pc_vmName'
    pc_gatewayMac = 'pc_gatewayMac'
    pc_gatewayIP = 'pc_gatewayIP'
    pc_volumeID = 'pc_volumeID'
    pc_remoteInfo1 = 'pc_remoteInfo1'
    pc_remoteInfo2 = 'pc_remoteInfo2'
    pc_remoteInfo3 = 'pc_remoteInfo3'
    pc_remoteInfo4 = 'pc_remoteInfo4'
    pc_remoteInfo5 = 'pc_remoteInfo5'
    pc_remoteInfo6 = 'pc_remoteInfo6'
    pc_remoteInfo7 = 'pc_remoteInfo7'
    pc_remoteInfo8 = 'pc_remoteInfo8'
    pc_remoteInfo9 = 'pc_remoteInfo9'
    pc_remoteInfo10 = 'pc_remoteInfo10'
    pc_foresicInfo = 'pc_foresicInfo'
    pc_isWinDefender = 'pc_isWinDefender'
    pc_isWinFirewall = 'pc_isWinFirewall'
    pc_isAutoPatch = 'pc_isAutoPatch'
    pc_isCertMisuse = 'pc_isCertMisuse'
    gi = 'gi'
    gm = 'gm'
    h1 = 'h1'
    h2 = 'h2'
    h3 = 'h3'
    HdModel = 'HdModel'
    l1 = 'l1'
    l2 = 'l2'
    l3 = 'l3'
    l4 = 'l4'
    l5 = 'l5'
    l6 = 'l6'
    m1 = 'm1'
    m2 = 'm2'
    m3 = 'm3'
    m4 = 'm4'
    m5 = 'm5'
    m6 = 'm6'
    FORGERY_MAC_ETH0_YN = 'FORGERY_MAC_ETH0_YN'
    FORGERY_MAC_ETH1_YN = 'FORGERY_MAC_ETH1_YN'
    FORGERY_MAC_ETH2_YN = 'FORGERY_MAC_ETH2_YN'
    FORGERY_MAC_ETH3_YN = 'FORGERY_MAC_ETH3_YN'
    FORGERY_MAC_ETH4_YN = 'FORGERY_MAC_ETH4_YN'
    FORGERY_MAC_ETH5_YN = 'FORGERY_MAC_ETH5_YN'
    FORGERY_MAC_YN = 'FORGERY_MAC_YN'
    cp = 'cp'
    mainboard = 'mainboard'
    os = 'os'
    OsLangCd = 'OsLangCd'
    OsRemoteYn = 'OsRemoteYn'
    OS_FIREWAll_CD = 'OS_FIREWAll_CD'
    BwVsnCd = 'BwVsnCd'
    p1 = 'p1'
    p2 = 'p2'
    p3 = 'p3'
    PRXY_LCAL = 'PRXY_LCAL'
    x1 = 'x1'
    x2 = 'x2'
    PrxyCntryCd = 'PrxyCntryCd'
    PubIPCntryCd = 'PubIPCntryCd'
    r1 = 'r1'
    r2 = 'r2'
    r3 = 'r3'
    REMOTE_YN = 'REMOTE_YN'
    RemoteIP = 'RemoteIP'
    RemotePORT = 'RemotePORT'
    RemoteProg = 'RemoteProg'
    rm1 = 'rm1'
    rm2 = 'rm2'
    rm3 = 'rm3'
    rm4 = 'rm4'
    rm5 = 'rm5'
    rm6 = 'rm6'
    rm7 = 'rm7'
    rm8 = 'rm8'
    rm9 = 'rm9'
    rm10 = 'rm10'
    SCAN_CNT_CURED = 'SCAN_CNT_CURED'
    SCAN_CNT_DETECT = 'SCAN_CNT_DETECT'
    vos_kind = 'vos_kind'
    vos_name = 'vos_name'
    VpnYn = 'VpnYn'
    IP_VPN_LCAL = 'IP_VPN_LCAL'
    vp = 'vp'
    vp2 = 'vp2'
    VpnCntryCd = 'VpnCntryCd'
    auth = 'auth'
    LogDate = 'LogDate'
    LogTime = 'LogTime'
    ELAPSED_TM = 'ELAPSED_TM'
    LOG_YN = 'LOG_YN'
    NAT_ERR_CD = 'NAT_ERR_CD'
    Madr1ValidYn = 'Madr1ValidYn'
    Madr2ValidYn = 'Madr2ValidYn'
    Madr3ValidYn = 'Madr3ValidYn'
    Madr4ValidYn = 'Madr4ValidYn'
    Madr5ValidYn = 'Madr5ValidYn'
    Madr6ValidYn = 'Madr6ValidYn'
    KbdType = 'KbdType'
    UsbSerial1 = 'UsbSerial1'
    UsbSerial2 = 'UsbSerial2'
    UsbSerial3 = 'UsbSerial3'
    RemoteEnv = 'RemoteEnv'
    OS_NM = 'OS_NM'
    OS_VSN_NM = 'OS_VSN_NM'
    hostname = 'hostname'
    OsTypeCd = 'OsTypeCd'
    OsVerCd = 'OsVerCd'
    OsSpCd = 'OsSpCd'
    OS_CD = 'OS_CD'
    OsGuid = 'OsGuid'
    windows_firewall = 'windows_firewall'
    MbManufacturer = 'MbManufacturer'
    MbProductNo = 'MbProductNo'
    sm_DI = 'sm_DI'
    sm_D1 = 'sm_D1'
    sm_D2 = 'sm_D2'
    sm_deviceId = 'sm_deviceId'
    sm_imei = 'sm_imei'
    sm_imsi = 'sm_imsi'
    sm_usim = 'sm_usim'
    sm_uuid = 'sm_uuid'
    sm_wifiMacAddr = 'sm_wifiMacAddr'
    sm_ethernetMacAddr = 'sm_ethernetMacAddr'
    sm_btMacAddr = 'sm_btMacAddr'
    sm_deviceModel = 'sm_deviceModel'
    sm_osVersion = 'sm_osVersion'
    sm_service = 'sm_service'
    sm_locale = 'sm_locale'
    sm_network = 'sm_network'
    sm_publicIP = 'sm_publicIP'
    sm_wifi_ip = 'sm_wifi_ip'
    sm_3g_ip = 'sm_3g_ip'
    sm_jailBreak = 'sm_jailBreak'
    sm_roaming = 'sm_roaming'
    sm_proxyIp = 'sm_proxyIp'
    sm_wifiApSsid = 'sm_wifiApSsid'
    sm_mobileAPSsid = 'sm_mobileAPSsid'
    sm_mobileNumber = 'sm_mobileNumber'
    sm_login_uuid = 'sm_login_uuid'
    COMMON_PUBLIC_IP_WAS = 'COMMON_PUBLIC_IP_WAS'
    workGbn = 'workGbn'
    workType = 'workType'
    securityMediaType = 'securityMediaType'
    totalScore = 'totalScore'
    executeTime = 'executeTime'
    responseCode = 'responseCode'
    blockingType = 'blockingType'
    country = 'country'
    doaddress = 'doaddress'
    processState = 'processState'
    comment = 'comment'
    isIdentified = 'isIdentified'
    isCertified = 'isCertified'
    hasReleaseDateTime = 'hasReleaseDateTime'
    releaseDateTime = 'releaseDateTime'
    personInCharge = 'personInCharge'
    completionDateTime = 'completionDateTime'
    WORK_GBN = 'WORK_GBN'
    FDS_IDEN = 'FDS_IDEN'
    E_FNC_AP_SVRNM = 'E_FNC_AP_SVRNM'
    RES_MSG = 'RES_MSG'
    E_FNC_TR_INNO = 'E_FNC_TR_INNO'
    message = 'message'
    pc_macAddr = 'pc_macAddr'
    pc_hddSerial = 'pc_hddSerial'
    pc_vpnIP = 'pc_vpnIP'


# INTERNAL CACHE DEVICEINFO SPLIT
# 내부 메모리에 저장할 단말기 정보(분할)
INTERNAL_DEVICEINFO_SPLIT = (("userId", "macAddr"),
                             ("macAddr", "userId"),
                             ("hddSerial", "userId"),
                             ("publicIP", "userId"),
                             ("userId", "uuid"),
                             ("uuid", "userId"),
                             ("imei", "userId"))


class ResponseLog:
    logId = 'logId'
    TR_DTM = 'TR_DTM'
    detectDateTime = 'detectDateTime'
    detectNanoTime = 'detectNanoTime'
    userId = 'userId'
    ruleId = 'ruleId'
    ruleGroupName = 'ruleGroupName'
    ruleType = 'ruleType'
    ruleName = 'ruleName'
    ruleDetail = 'ruleDetail'
    score = 'score'
    blockingType = 'blockingType'
    EBNK_MED_DSC = 'EBNK_MED_DSC'
    message = 'message'


class OneWayMessageLog:
    TR_DTM = 'TR_DTM'
    E_FNC_USRID = 'E_FNC_USRID'
    STD_GBL_ID = 'STD_GBL_ID'
    workGbn = 'workGbn'
    fdsIden = 'fdsIden'
    message = 'message'


class MessageCommon(Enum):
    NAAC_DSC = ("중앙회조합구분코드", "NAAC_DSC")
    EBNK_MED_DSC = ("E뱅킹매체구분코드", "EBNK_MED_DSC")
    E_FNC_CUSNO = ("E금융고객번호", "E_FNC_CUSNO")
    E_FNC_USRID = ("E금융이용자ID", "E_FNC_USRID")
    E_FNC_COPR_ID = ("E금융기업ID", "E_FNC_COPR_ID")
    COPR_DS = ("기업구분", "COPR_DS")
    LANG_DS = ("언어구분", "LANG_DS")
    E_FNC_USR_OS_DSC = ("E금융사용자운영체제구분코드", "E_FNC_USR_OS_DSC")
    E_FNC_USR_TELNO = ("E금융사용자전화번호", "E_FNC_USR_TELNO")
    E_FNC_USR_IPADR = ("E금융사용자IP주소", "E_FNC_USR_IPADR")
    E_FNC_LGIN_DSC = ("E금융로그인구분코드", "E_FNC_LGIN_DSC")
    E_FNC_TR_ACNO = ("E금융거래계좌번호", "E_FNC_TR_ACNO")
    RMS_SVC_C = ("수신서비스코드", "RMS_SVC_C")
    INQ_CND_CLF_ID = ("조회조건분류ID", "INQ_CND_CLF_ID")
    INQ_CND_VAL = ("조회조건값", "INQ_CND_VAL")
    E_FNC_USR_DVIC_INF_CNTN = ("E금융사용자디바이스정보내용", "E_FNC_USR_DVIC_INF_CNTN")
    E_FNC_USR_ACS_DSC = ("E금융사용자접근구분코드", "E_FNC_USR_ACS_DSC")
    E_FNC_MED_SVCID = ("E금융매체서비스ID", "E_FNC_MED_SVCID")
    E_FNC_MED_SVRNM = ("E금융매체서버명", "E_FNC_MED_SVRNM")
    E_FNC_RSP_C = ("E금융응답코드", "E_FNC_RSP_C")
    EXE_YN = ("실행여부", "EXE_YN")
    Amount = ("금액", "Amount")
    E_FNC_TR_INNO = ("타계좌구분코드", "E_FNC_TR_INNO")
    E_FNC_TR_ACNO_C = ("입금계좌번호", "E_FNC_TR_ACNO_C")
    STD_GBL_ID = ("표준글로벌ID", "STD_GBL_ID")
    WORK_GBN = ("부가서비스유형", "WORK_GBN")
    FDS_IDEN = ("부가서비스구분", "FDS_IDEN")
    E_FNC_AP_SVRNM = ("타계좌구분코드", "E_FNC_AP_SVRNM")
    TRANSFER_ACNO = ("입금계좌번호", "TRANSFER_ACNO")
    CST_NAM = ("고객성명", "CST_NAM")
    COMMON_PUBLIC_IP = ("공인IP WAS", "COMMON_PUBLIC_IP")
    IO_EA_DD1_FTR_LMT3 = ("1일이체한도(만원)", "IO_EA_DD1_FTR_LMT3")
    IO_EA_TM1_FTR_LMT3 = ("1회이체한도(만원)", "IO_EA_TM1_FTR_LMT3")
    IO_EA_PW_CD_DS1 = ("보안매체 오류횟수", "IO_EA_PW_CD_DS1")
    IO_EA_PW_CD_DS2 = ("보안매체 종류코드", "IO_EA_PW_CD_DS2")
    IO_EA_PW_CD_DS3 = ("키락이용여부", "IO_EA_PW_CD_DS3")
    PRE_ASSIGN_YN = ("단말기지정여부", "PRE_ASSIGN_YN")
    SMS_AUTHEN_YN = ("휴대폰SMS인증여부", "SMS_AUTHEN_YN")
    EXCEPT_REGIST = ("예외고객등록여부", "EXCEPT_REGIST")
    EXCEPTION_ADD_AUTHEN_YN = ("SMS통지가입여부", "EXCEPTION_ADD_AUTHEN_YN")
    SMART_AUTHEN_YN = ("앱인증서비스", "SMART_AUTHEN_YN")
    ATTC_DS = ("전화승인서비스 5회 오류", "ATTC_DS")
    CHRR_TELNO = ("전화승인 전화번호1", "CHRR_TELNO")
    CHRR_TELNO1 = ("전화승인 전화번호2", "CHRR_TELNO1")
    RG_TELNO = ("전화승인 전화번호3", "RG_TELNO")
    FTR_DS2 = ("이체구분", "FTR_DS2")
    LS_FTR_TRDT = ("최종이체거래일", "LS_FTR_TRDT")
    LS_TRDT = ("최종 로그인일자", "LS_TRDT")
    RV_AC_DGN_YN2 = ("입금계좌지정여부", "RV_AC_DGN_YN2")
    IO_EA_DRW_AC_NAME1 = ("출금계좌이름", "IO_EA_DRW_AC_NAME1")
    IO_EA_RV_ACTNM1 = ("입금계좌이름", "IO_EA_RV_ACTNM1")
    IO_EA_DPZ_PL_IMP_BAC = ("수신지불가능잔액", "IO_EA_DPZ_PL_IMP_BAC")
    IO_EA_TOT_BAC6 = ("출금후 잔액", "IO_EA_TOT_BAC6")
    IO_EA_RMT_FEE1 = ("송금수수료", "IO_EA_RMT_FEE1")

    def __init__(self, field_name, key):
        self.field_name = field_name
        self.key = key


class MessageSmart(Enum):
    sm_DI = ("기기ID 파트1", "sm_DI")
    sm_D1 = ("기기ID 파트2", "sm_D1")
    sm_D2 = ("기기ID 파트3", "sm_D2")
    sm_deviceId = ("기기일련번호", "sm_deviceId")
    sm_imei = ("IMEI", "sm_imei")
    sm_imsi = ("IMSI", "sm_imsi")
    sm_usim = ("USIM 일련번호", "sm_usim")
    sm_uuid = ("UUID", "sm_uuid")
    sm_wifiMacAddr = ("Wi-Fi MAC", "sm_wifiMacAddr")
    sm_ethernetMacAddr = ("이더넷 MAC", "sm_ethernetMacAddr")
    sm_btMacAddr = ("블루투스 MAC", "sm_btMacAddr")
    sm_deviceModel = ("기기모델명", "sm_deviceModel")
    sm_osVersion = ("운영체제버전", "sm_osVersion")
    sm_service = ("통신사업자", "sm_service")
    sm_locale = ("핸드폰언어설정", "sm_locale")
    sm_network = ("네트워크상태", "sm_network")
    sm_publicIP = ("스마트 공인IP", "sm_publicIP")
    sm_wifi_ip = ("Wi-Fi 내부 IP", "sm_wifi_ip")
    sm_3g_ip = ("3G 내부 IP", "sm_3g_ip")
    sm_jailBreak = ("루팅, 탈옥여부", "sm_jailBreak")
    sm_roaming = ("로밍여부", "sm_roaming")
    sm_proxyIp = ("프록시IP", "sm_proxyIp")
    sm_wifiApSsid = ("WiFi AP SID", "sm_wifiApSsid")
    sm_mobileAPSsid = ("통신사", "sm_mobileAPSsid")
    sm_mobileNumber = ("전화번호", "sm_mobileNumber")
    sm_login_uuid = ("기기 UUID_WAS", "sm_login_uuid")

    def __init__(self, field_name, key):
        self.field_name = field_name
        self.key = key


class MessageStrMapCommon(Enum):
    nbnk_c = ("nbnk_c", "NBNK_C")
    isForeigner = ("isForeigner", "isForeigner")
    isNewAccount = ("isNewAccount", "isNewAccount")
    isNewDevice = ("isNewDevice", "isNewDevice")
    isForeignMobile = ("isForeignMobile", "pc_winVer")
    isWarningProgram = ("isWarningProgram", "pc_volumeID")
    yearOfBirth = ("yearOfBirth", "pc_foresicInfo")
    gender = ("gender", "pc_isWinFirewall")

    def __init__(self, key, es_name):
        self.key = key
        self.es_name = es_name


class MessageAstx(Enum):
    p1 = ("공인IP1", "p1", "pc_publicIP1")
    r1 = ("사설IP1", "r1", "pc_privateIP1")
    r2 = ("사설IP2", "r2", "pc_privateIP2")
    r3 = ("사설IP3", "r3", "pc_privateIP3")
    pc_isProxy = ("Proxy유무", "pc_isProxy", "pc_isProxy")
    PRXY_LCAL = ("Proxy IP1", "PRXY_LCAL", "pc_proxyIP1")
    x1 = ("Proxy IP2", "x1", "pc_proxyIP2")
    VpnYn = ("VPN유무", "VpnYn", "pc_isVpn")
    IP_VPN_LCAL = ("VPN IP1", "IP_VPN_LCAL", "pc_vpnIP1")
    vp = ("VPN IP2", "vp", "pc_vpnIP2")
    m1 = ("MAC Address 1", "m1", "pc_macAddr1")
    m2 = ("MAC Address 2", "m2", "pc_macAddr2")
    m3 = ("MAC Address 3", "m3", "pc_macAddr3")
    m4 = ("MAC Address 4", "m4", "pc_macAddr4")
    m5 = ("MAC Address 5", "m5", "pc_macAddr5")
    m6 = ("MAC Address 6", "m6", "pc_macAddr6")
    l1 = ("논리 MAC1", "l1", "pc_logicalMac1")
    l2 = ("논리 MAC2", "l2", "pc_logicalMac2")
    l3 = ("논리 MAC3", "l3", "pc_logicalMac3")
    l4 = ("논리 MAC4", "l4", "pc_logicalMac4")
    l5 = ("논리 MAC5", "l5", "pc_logicalMac5")
    l6 = ("논리 MAC6", "l6", "pc_logicalMac6")
    h1 = ("HDD Serial1", "h1", "pc_hddSerial1")
    h2 = ("HDD Serial2", "h2", "pc_hddSerial2")
    h3 = ("HDD Serial3", "h3", "pc_hddSerial3")
    mainboard = ("Mainboard SN", "mainboard", "pc_mbSn")
    vos_kind = ("가상OS사용여부", "vos_kind", "pc_isVm")
    vos_name = ("가상OS명", "vos_name", "pc_vmName")
    gm = ("게이트웨이MAC", "gm", "pc_gatewayMac")
    gi = ("게이트웨이IP", "gi", "pc_gatewayIP")
    rm1 = ("원격정보1", "rm1", "pc_remoteInfo1")
    rm2 = ("원격정보2", "rm2", "pc_remoteInfo2")
    rm3 = ("원격정보3", "rm3", "pc_remoteInfo3")
    rm4 = ("원격정보4", "rm4", "pc_remoteInfo4")
    rm5 = ("원격정보5", "rm5", "pc_remoteInfo5")
    rm6 = ("원격정보6", "rm6", "pc_remoteInfo6")
    rm7 = ("원격정보7", "rm7", "pc_remoteInfo7")
    rm8 = ("원격정보8", "rm8", "pc_remoteInfo8")
    rm9 = ("원격정보9", "rm9", "pc_remoteInfo9")
    rm10 = ("원격정보10", "rm10", "pc_remoteInfo10")
    auth = ("공인인증서 오용검사", "auth", "pc_isCertMisuse")
    HdModel = ("HDD MODEL NUMBER", "HdModel", "pc_HdModel")
    SCAN_CNT_CURED = ("악성코드 치료 건수", "SCAN_CNT_CURED", "pc_SCAN_CNT_CURED")
    SCAN_CNT_DETECT = ("악성코드 탐지 건수", "SCAN_CNT_DETECT", "pc_SCAN_CNT_DETECT")
    VpnCntryCd = ("VPN 국가코드", "VpnCntryCd", "pc_VpnCntryCd")
    REMOTE_YN = ("원격환경에서의 구동여부", "REMOTE_YN", "pc_REMOTE_YN")
    RemoteIP = ("원격접속 remote IP", "RemoteIP", "pc_RemoteIP")
    RemotePORT = ("원격접속 remote Port", "RemotePORT", "pc_RemotePORT")
    RemoteProg = ("원격프로그램명", "RemoteProg", "pc_RemoteProg")
    PrxyCntryCd = ("Proxy 국가코드", "PrxyCntryCd", "pc_PrxyCntryCd")
    PubIPCntryCd = ("공인 IP 국가코드", "PubIPCntryCd", "pc_PubIPCntryCd")
    FORGERY_MAC_ETH0_YN = ("MAC Address 1 변조여부", "FORGERY_MAC_ETH0_YN", "pc_FORGERY_MAC_ETH0_YN")
    FORGERY_MAC_ETH1_YN = ("MAC Address 2 변조여부", "FORGERY_MAC_ETH1_YN", "pc_FORGERY_MAC_ETH1_YN")
    FORGERY_MAC_ETH2_YN = ("MAC Address 3 변조여부", "FORGERY_MAC_ETH2_YN", "pc_FORGERY_MAC_ETH2_YN")
    FORGERY_MAC_ETH3_YN = ("MAC Address 4 변조여부", "FORGERY_MAC_ETH3_YN", "pc_FORGERY_MAC_ETH3_YN")
    FORGERY_MAC_ETH4_YN = ("MAC Address 5 변조여부", "FORGERY_MAC_ETH4_YN", "pc_FORGERY_MAC_ETH4_YN")
    FORGERY_MAC_ETH5_YN = ("MAC Address 6 변조여부", "FORGERY_MAC_ETH5_YN", "pc_FORGERY_MAC_ETH5_YN")
    FORGERY_MAC_YN = ("MAC Address 통합변조여부", "FORGERY_MAC_YN", "pc_FORGERY_MAC_YN")
    os = ("운영체제 코드", "os", "pc_os")
    OsLangCd = ("운영체제 언어팩", "OsLangCd", "pc_OsLangCd")
    OsRemoteYn = ("운영체제 원격접속 허용 여부", "OsRemoteYn", "pc_OsRemoteYn")
    OS_FIREWALL_CD = ("운영체제 방화벽 설정 코드", "OS_FIREWALL_CD", "pc_OS_FIREWALL_CD")
    BwVsnCd = ("브라우저 버전코드", "BwVsnCd", "pc_BwVsnCd")
    KbdType = ("키보드 타입코드", "KbdType", "")
    UsbSerial1 = ("USB 시리얼 1", "UsbSerial1", "")
    UsbSerial2 = ("USB 시리얼 2", "UsbSerial2", "")
    UsbSerial3 = ("USB 시리얼 3", "UsbSerial3", "")
    RemoteEnv = ("원격환경에서의 구동정보(제외)", "RemoteEnv", "")
    OS_NM = ("OS 이름 스트링", "OS_NM", "")
    OS_VSN_NM = ("OS 버전 스트링", "OS_VSN_NM", "")
    hostname = ("PC 호스트 이름", "hostname", "")
    OsTypeCd = ("운영체제타입코드", "OsTypeCd", "")
    OsVerCd = ("운영체제버전코드", "OsVerCd", "")
    OsSpCd = ("windows 서비스팩 메이저버전", "OsSpCd", "")
    OS_CD = ("운영체제구분", "OS_CD", "")
    OsGuid = ("운영체제 식별번호", "OsGuid", "")
    windows_firewall = ("운영체제 방화벽 설정 코드", "windows_firewall", "")
    MbManufacturer = ("마더보드 제조업체", "MbManufacturer", "")
    MbProductNo = ("마더보드 Product No.", "MbProductNo", "")
    Madr1ValidYn = ("Mac Address 1 유효성여부", "Madr1ValidYn", "")
    Madr2ValidYn = ("Mac Address 2 유효성여부", "Madr2ValidYn", "")
    Madr3ValidYn = ("Mac Address 3 유효성여부", "Madr3ValidYn", "")
    Madr4ValidYn = ("Mac Address 4 유효성여부", "Madr4ValidYn", "")
    Madr5ValidYn = ("Mac Address 5 유효성여부", "Madr5ValidYn", "")
    Madr6ValidYn = ("Mac Address 6 유효성여부", "Madr6ValidYn", "")
    LogDate = ("수집일자", "LogDate", "")
    LogTime = ("수집시간", "LogTime", "")
    ELAPSED_TM = ("로그수집소요시간", "ELAPSED_TM", "")
    LOG_YN = ("로그수집여부", "LOG_YN", "")
    NAT_ERR_CD = ("NAT IP 수집구분", "NAT_ERR_CD", "")
    x2 = ("Proxy IP 2", "x2", "")
    vp2 = ("VPN IP 2", "vp2", "")

    def __init__(self, field_name, astx_name, es_name):
        self.field_name = field_name
        self.astx_name = astx_name
        self.es_name = es_name
